#!/usr/bin/env python
# -*- coding: UTF8 -*-

# Python module gesjo5.py
# Autogenerated from gesjo5.glade
# Generated on Thu Dec 22 18:22:21 2005

# Warning: Do not modify any context comment such as #--
# They are required to keep user's code

import os

import gtk

from SimpleGladeApp import SimpleGladeApp
from SimpleGladeApp import bindtextdomain

app_name = "gesjo5"
app_version = "0.0.1"

glade_dir = ""
locale_dir = ""

bindtextdomain(app_name, locale_dir)


class Frmgesjo(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frmgesjo",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmgesjo.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmgesjo.new }

    #-- Frmgesjo custom methods {
    #   Write your own methods here
    #-- Frmgesjo custom methods }

    #-- Frmgesjo.on_nou1_activate {
    def on_nou1_activate(self, widget, *args):
        print "on_nou1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_nou1_activate }

    #-- Frmgesjo.on_obre1_activate {
    def on_obre1_activate(self, widget, *args):
        print "on_obre1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_obre1_activate }

    #-- Frmgesjo.on_desa1_activate {
    def on_desa1_activate(self, widget, *args):
        print "on_desa1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_desa1_activate }

    #-- Frmgesjo.on_desa_com1_activate {
    def on_desa_com1_activate(self, widget, *args):
        print "on_desa_com1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_desa_com1_activate }

    #-- Frmgesjo.on_mnsurt_activate {
    def on_mnsurt_activate(self, widget, *args):
        print "on_mnsurt_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_mnsurt_activate }

    #-- Frmgesjo.on_talla1_activate {
    def on_talla1_activate(self, widget, *args):
        print "on_talla1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_talla1_activate }

    #-- Frmgesjo.on_copia1_activate {
    def on_copia1_activate(self, widget, *args):
        print "on_copia1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_copia1_activate }

    #-- Frmgesjo.on_enganxa1_activate {
    def on_enganxa1_activate(self, widget, *args):
        print "on_enganxa1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_enganxa1_activate }

    #-- Frmgesjo.on_esborra1_activate {
    def on_esborra1_activate(self, widget, *args):
        print "on_esborra1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_esborra1_activate }

    #-- Frmgesjo.on_clients1_activate {
    def on_clients1_activate(self, widget, *args):
        print "on_clients1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_clients1_activate }

    #-- Frmgesjo.on_arreglos1_activate {
    def on_arreglos1_activate(self, widget, *args):
        print "on_arreglos1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_arreglos1_activate }

    #-- Frmgesjo.on_taller1_activate {
    def on_taller1_activate(self, widget, *args):
        print "on_taller1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_taller1_activate }

    #-- Frmgesjo.on_factures1_activate {
    def on_factures1_activate(self, widget, *args):
        print "on_factures1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_factures1_activate }

    #-- Frmgesjo.on_informes1_activate {
    def on_informes1_activate(self, widget, *args):
        print "on_informes1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_informes1_activate }

    #-- Frmgesjo.on_manteniment1_activate {
    def on_manteniment1_activate(self, widget, *args):
        print "on_manteniment1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_manteniment1_activate }

    #-- Frmgesjo.on_mntallers_activate_item {
    def on_mntallers_activate_item(self, widget, *args):
        print "on_mntallers_activate_item called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_mntallers_activate_item }

    #-- Frmgesjo.on_mnmecanics_activate_item {
    def on_mnmecanics_activate_item(self, widget, *args):
        print "on_mnmecanics_activate_item called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_mnmecanics_activate_item }

    #-- Frmgesjo.on_mnmarques_activate_item {
    def on_mnmarques_activate_item(self, widget, *args):
        print "on_mnmarques_activate_item called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_mnmarques_activate_item }

    #-- Frmgesjo.on_clients2_activate {
    def on_clients2_activate(self, widget, *args):
        print "on_clients2_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_clients2_activate }

    #-- Frmgesjo.on_arreglos2_activate {
    def on_arreglos2_activate(self, widget, *args):
        print "on_arreglos2_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_arreglos2_activate }

    #-- Frmgesjo.on_quant_a1_activate {
    def on_quant_a1_activate(self, widget, *args):
        print "on_quant_a1_activate called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_quant_a1_activate }

    #-- Frmgesjo.on_btclients_clicked {
    def on_btclients_clicked(self, widget, *args):
        print "on_btclients_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_btclients_clicked }

    #-- Frmgesjo.on_btarreglos_clicked {
    def on_btarreglos_clicked(self, widget, *args):
        print "on_btarreglos_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_btarreglos_clicked }

    #-- Frmgesjo.on_btinformes_clicked {
    def on_btinformes_clicked(self, widget, *args):
        print "on_btinformes_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_btinformes_clicked }

    #-- Frmgesjo.on_btsurt_clicked {
    def on_btsurt_clicked(self, widget, *args):
        print "on_btsurt_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_btsurt_clicked }

    #-- Frmgesjo.on_bt_cl_nou_clicked {
    def on_bt_cl_nou_clicked(self, widget, *args):
        print "on_bt_cl_nou_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_nou_clicked }

    #-- Frmgesjo.on_bt_cl_edita_clicked {
    def on_bt_cl_edita_clicked(self, widget, *args):
        print "on_bt_cl_edita_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_edita_clicked }

    #-- Frmgesjo.on_bt_cl_esborra_clicked {
    def on_bt_cl_esborra_clicked(self, widget, *args):
        print "on_bt_cl_esborra_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_esborra_clicked }

    #-- Frmgesjo.on_bt_cl_arreglos_clicked {
    def on_bt_cl_arreglos_clicked(self, widget, *args):
        print "on_bt_cl_arreglos_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_arreglos_clicked }

    #-- Frmgesjo.on_bt_cl_imprimeix_clicked {
    def on_bt_cl_imprimeix_clicked(self, widget, *args):
        print "on_bt_cl_imprimeix_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_imprimeix_clicked }

    #-- Frmgesjo.on_bt_cl_primer_clicked {
    def on_bt_cl_primer_clicked(self, widget, *args):
        print "on_bt_cl_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_primer_clicked }

    #-- Frmgesjo.on_bt_cl_anterior_clicked {
    def on_bt_cl_anterior_clicked(self, widget, *args):
        print "on_bt_cl_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_anterior_clicked }

    #-- Frmgesjo.on_bt_cl_seguent_clicked {
    def on_bt_cl_seguent_clicked(self, widget, *args):
        print "on_bt_cl_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_seguent_clicked }

    #-- Frmgesjo.on_bt_cl_darrer_clicked {
    def on_bt_cl_darrer_clicked(self, widget, *args):
        print "on_bt_cl_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_darrer_clicked }

    #-- Frmgesjo.on_bt_cl_cerca_clicked {
    def on_bt_cl_cerca_clicked(self, widget, *args):
        print "on_bt_cl_cerca_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_cerca_clicked }

    #-- Frmgesjo.on_bt_cl_aplica_clicked {
    def on_bt_cl_aplica_clicked(self, widget, *args):
        print "on_bt_cl_aplica_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_aplica_clicked }

    #-- Frmgesjo.on_bt_cl_cancel_clicked {
    def on_bt_cl_cancel_clicked(self, widget, *args):
        print "on_bt_cl_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_cl_cancel_clicked }

    #-- Frmgesjo.on_bt_ar_nou_clicked {
    def on_bt_ar_nou_clicked(self, widget, *args):
        print "on_bt_ar_nou_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_nou_clicked }

    #-- Frmgesjo.on_bt_ar_edita_clicked {
    def on_bt_ar_edita_clicked(self, widget, *args):
        print "on_bt_ar_edita_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_edita_clicked }

    #-- Frmgesjo.on_bt_ar_esborra_clicked {
    def on_bt_ar_esborra_clicked(self, widget, *args):
        print "on_bt_ar_esborra_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_esborra_clicked }

    #-- Frmgesjo.on_bt_ar_client_clicked {
    def on_bt_ar_client_clicked(self, widget, *args):
        print "on_bt_ar_client_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_client_clicked }

    #-- Frmgesjo.on_bt_ar_imprimeix_clicked {
    def on_bt_ar_imprimeix_clicked(self, widget, *args):
        print "on_bt_ar_imprimeix_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_imprimeix_clicked }

    #-- Frmgesjo.on_bt_ar_cerca_dt_entrada_clicked {
    def on_bt_ar_cerca_dt_entrada_clicked(self, widget, *args):
        print "on_bt_ar_cerca_dt_entrada_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_cerca_dt_entrada_clicked }

    #-- Frmgesjo.on_bt_ar_primer_clicked {
    def on_bt_ar_primer_clicked(self, widget, *args):
        print "on_bt_ar_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_primer_clicked }

    #-- Frmgesjo.on_bt_ar_anterior_clicked {
    def on_bt_ar_anterior_clicked(self, widget, *args):
        print "on_bt_ar_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_anterior_clicked }

    #-- Frmgesjo.on_bt_ar_seguent_clicked {
    def on_bt_ar_seguent_clicked(self, widget, *args):
        print "on_bt_ar_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_seguent_clicked }

    #-- Frmgesjo.on_bt_ar_darrer_clicked {
    def on_bt_ar_darrer_clicked(self, widget, *args):
        print "on_bt_ar_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_darrer_clicked }

    #-- Frmgesjo.on_bt_ar_cerca_clicked {
    def on_bt_ar_cerca_clicked(self, widget, *args):
        print "on_bt_ar_cerca_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_cerca_clicked }

    #-- Frmgesjo.on_bt_ar_aplica_clicked {
    def on_bt_ar_aplica_clicked(self, widget, *args):
        print "on_bt_ar_aplica_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_aplica_clicked }

    #-- Frmgesjo.on_bt_ar_cancel_clicked {
    def on_bt_ar_cancel_clicked(self, widget, *args):
        print "on_bt_ar_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_ar_cancel_clicked }

    #-- Frmgesjo.on_in_arreglos_tots_clicked {
    def on_in_arreglos_tots_clicked(self, widget, *args):
        print "on_in_arreglos_tots_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_in_arreglos_tots_clicked }

    #-- Frmgesjo.on_bt_in_ar_sobres_clicked {
    def on_bt_in_ar_sobres_clicked(self, widget, *args):
        print "on_bt_in_ar_sobres_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_bt_in_ar_sobres_clicked }

    #-- Frmgesjo.on_in_llistats_tallers_clicked {
    def on_in_llistats_tallers_clicked(self, widget, *args):
        print "on_in_llistats_tallers_clicked called with self.%s" % widget.get_name()
    #-- Frmgesjo.on_in_llistats_tallers_clicked }


class FrmDlEsborra(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frm_dl_esborra",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- FrmDlEsborra.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- FrmDlEsborra.new }

    #-- FrmDlEsborra custom methods {
    #   Write your own methods here
    #-- FrmDlEsborra custom methods }

    #-- FrmDlEsborra.on_bt_dl_esborra_cancel_clicked {
    def on_bt_dl_esborra_cancel_clicked(self, widget, *args):
        print "on_bt_dl_esborra_cancel_clicked called with self.%s" % widget.get_name()
    #-- FrmDlEsborra.on_bt_dl_esborra_cancel_clicked }

    #-- FrmDlEsborra.on_bt_dl_dacord_clicked {
    def on_bt_dl_dacord_clicked(self, widget, *args):
        print "on_bt_dl_dacord_clicked called with self.%s" % widget.get_name()
    #-- FrmDlEsborra.on_bt_dl_dacord_clicked }


class DlgCerca(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="dlg_cerca",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- DlgCerca.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- DlgCerca.new }

    #-- DlgCerca custom methods {
    #   Write your own methods here
    #-- DlgCerca custom methods }


class Frmmarca(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frmmarca",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmmarca.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmmarca.new }

    #-- Frmmarca custom methods {
    #   Write your own methods here
    #-- Frmmarca custom methods }

    #-- Frmmarca.on_bt_ma_nou_clicked {
    def on_bt_ma_nou_clicked(self, widget, *args):
        print "on_bt_ma_nou_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_nou_clicked }

    #-- Frmmarca.on_bt_ma_edita_clicked {
    def on_bt_ma_edita_clicked(self, widget, *args):
        print "on_bt_ma_edita_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_edita_clicked }

    #-- Frmmarca.on_bt_ma_esborra_clicked {
    def on_bt_ma_esborra_clicked(self, widget, *args):
        print "on_bt_ma_esborra_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_esborra_clicked }

    #-- Frmmarca.on_bt_cl_arreglos_clicked {
    def on_bt_cl_arreglos_clicked(self, widget, *args):
        print "on_bt_cl_arreglos_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_cl_arreglos_clicked }

    #-- Frmmarca.on_bt_cl_imprimeix_clicked {
    def on_bt_cl_imprimeix_clicked(self, widget, *args):
        print "on_bt_cl_imprimeix_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_cl_imprimeix_clicked }

    #-- Frmmarca.on_bt_ma_tanca_clicked {
    def on_bt_ma_tanca_clicked(self, widget, *args):
        print "on_bt_ma_tanca_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_tanca_clicked }

    #-- Frmmarca.on_bt_ma_primer_clicked {
    def on_bt_ma_primer_clicked(self, widget, *args):
        print "on_bt_ma_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_primer_clicked }

    #-- Frmmarca.on_bt_ma_anterior_clicked {
    def on_bt_ma_anterior_clicked(self, widget, *args):
        print "on_bt_ma_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_anterior_clicked }

    #-- Frmmarca.on_bt_ma_seguent_clicked {
    def on_bt_ma_seguent_clicked(self, widget, *args):
        print "on_bt_ma_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_seguent_clicked }

    #-- Frmmarca.on_bt_ma_darrer_clicked {
    def on_bt_ma_darrer_clicked(self, widget, *args):
        print "on_bt_ma_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_darrer_clicked }

    #-- Frmmarca.on_bt_ma_cerca_clicked {
    def on_bt_ma_cerca_clicked(self, widget, *args):
        print "on_bt_ma_cerca_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_cerca_clicked }

    #-- Frmmarca.on_bt_ma_aplica_clicked {
    def on_bt_ma_aplica_clicked(self, widget, *args):
        print "on_bt_ma_aplica_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_aplica_clicked }

    #-- Frmmarca.on_bt_ma_cancel_clicked {
    def on_bt_ma_cancel_clicked(self, widget, *args):
        print "on_bt_ma_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmmarca.on_bt_ma_cancel_clicked }


class Frmtaller(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frmtaller",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmtaller.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmtaller.new }

    #-- Frmtaller custom methods {
    #   Write your own methods here
    #-- Frmtaller custom methods }

    #-- Frmtaller.on_bt_ta_nou_clicked {
    def on_bt_ta_nou_clicked(self, widget, *args):
        print "on_bt_ta_nou_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_nou_clicked }

    #-- Frmtaller.on_bt_ta_edita_clicked {
    def on_bt_ta_edita_clicked(self, widget, *args):
        print "on_bt_ta_edita_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_edita_clicked }

    #-- Frmtaller.on_bt_ta_esborra_clicked {
    def on_bt_ta_esborra_clicked(self, widget, *args):
        print "on_bt_ta_esborra_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_esborra_clicked }

    #-- Frmtaller.on_bt_ta_mecanics_clicked {
    def on_bt_ta_mecanics_clicked(self, widget, *args):
        print "on_bt_ta_mecanics_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_mecanics_clicked }

    #-- Frmtaller.on_button82_clicked {
    def on_button82_clicked(self, widget, *args):
        print "on_button82_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_button82_clicked }

    #-- Frmtaller.on_bt_ta_tanca_clicked {
    def on_bt_ta_tanca_clicked(self, widget, *args):
        print "on_bt_ta_tanca_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_tanca_clicked }

    #-- Frmtaller.on_bt_ta_primer_clicked {
    def on_bt_ta_primer_clicked(self, widget, *args):
        print "on_bt_ta_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_primer_clicked }

    #-- Frmtaller.on_bt_ta_anterior_clicked {
    def on_bt_ta_anterior_clicked(self, widget, *args):
        print "on_bt_ta_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_anterior_clicked }

    #-- Frmtaller.on_bt_ta_seguent_clicked {
    def on_bt_ta_seguent_clicked(self, widget, *args):
        print "on_bt_ta_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_seguent_clicked }

    #-- Frmtaller.on_bt_ta_darrer_clicked {
    def on_bt_ta_darrer_clicked(self, widget, *args):
        print "on_bt_ta_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_darrer_clicked }

    #-- Frmtaller.on_bt_ta_cerca_clicked {
    def on_bt_ta_cerca_clicked(self, widget, *args):
        print "on_bt_ta_cerca_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_cerca_clicked }

    #-- Frmtaller.on_bt_ta_aplica_clicked {
    def on_bt_ta_aplica_clicked(self, widget, *args):
        print "on_bt_ta_aplica_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_aplica_clicked }

    #-- Frmtaller.on_bt_ta_cancel_clicked {
    def on_bt_ta_cancel_clicked(self, widget, *args):
        print "on_bt_ta_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmtaller.on_bt_ta_cancel_clicked }


class Frmmecanic(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frmmecanic",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmmecanic.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmmecanic.new }

    #-- Frmmecanic custom methods {
    #   Write your own methods here
    #-- Frmmecanic custom methods }

    #-- Frmmecanic.on_bt_me_nou_clicked {
    def on_bt_me_nou_clicked(self, widget, *args):
        print "on_bt_me_nou_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_nou_clicked }

    #-- Frmmecanic.on_bt_me_edita_clicked {
    def on_bt_me_edita_clicked(self, widget, *args):
        print "on_bt_me_edita_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_edita_clicked }

    #-- Frmmecanic.on_bt_me_esborra_clicked {
    def on_bt_me_esborra_clicked(self, widget, *args):
        print "on_bt_me_esborra_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_esborra_clicked }

    #-- Frmmecanic.on_bt_me_tallers_clicked {
    def on_bt_me_tallers_clicked(self, widget, *args):
        print "on_bt_me_tallers_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_tallers_clicked }

    #-- Frmmecanic.on_bt_me_imprimeix_clicked {
    def on_bt_me_imprimeix_clicked(self, widget, *args):
        print "on_bt_me_imprimeix_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_imprimeix_clicked }

    #-- Frmmecanic.on_bt_me_tanca_clicked {
    def on_bt_me_tanca_clicked(self, widget, *args):
        print "on_bt_me_tanca_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_tanca_clicked }

    #-- Frmmecanic.on_bt_me_cerca_taller_clicked {
    def on_bt_me_cerca_taller_clicked(self, widget, *args):
        print "on_bt_me_cerca_taller_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_cerca_taller_clicked }

    #-- Frmmecanic.on_bt_me_primer_clicked {
    def on_bt_me_primer_clicked(self, widget, *args):
        print "on_bt_me_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_primer_clicked }

    #-- Frmmecanic.on_bt_me_anterior_clicked {
    def on_bt_me_anterior_clicked(self, widget, *args):
        print "on_bt_me_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_anterior_clicked }

    #-- Frmmecanic.on_bt_me_seguent_clicked {
    def on_bt_me_seguent_clicked(self, widget, *args):
        print "on_bt_me_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_seguent_clicked }

    #-- Frmmecanic.on_bt_me_darrer_clicked {
    def on_bt_me_darrer_clicked(self, widget, *args):
        print "on_bt_me_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_darrer_clicked }

    #-- Frmmecanic.on_bt_me_cerca_clicked {
    def on_bt_me_cerca_clicked(self, widget, *args):
        print "on_bt_me_cerca_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_cerca_clicked }

    #-- Frmmecanic.on_bt_me_aplica_clicked {
    def on_bt_me_aplica_clicked(self, widget, *args):
        print "on_bt_me_aplica_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_aplica_clicked }

    #-- Frmmecanic.on_bt_me_cancel_clicked {
    def on_bt_me_cancel_clicked(self, widget, *args):
        print "on_bt_me_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmmecanic.on_bt_me_cancel_clicked }


class Frmbrowse(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="frmbrowse",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmbrowse.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmbrowse.new }

    #-- Frmbrowse custom methods {
    #   Write your own methods here
    #-- Frmbrowse custom methods }

    #-- Frmbrowse.on_brw_select_cursor_row {
    def on_brw_select_cursor_row(self, widget, *args):
        print "on_brw_select_cursor_row called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_brw_select_cursor_row }

    #-- Frmbrowse.on_bt_ta_primer_clicked {
    def on_bt_ta_primer_clicked(self, widget, *args):
        print "on_bt_ta_primer_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_ta_primer_clicked }

    #-- Frmbrowse.on_bt_ta_anterior_clicked {
    def on_bt_ta_anterior_clicked(self, widget, *args):
        print "on_bt_ta_anterior_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_ta_anterior_clicked }

    #-- Frmbrowse.on_bt_ta_seguent_clicked {
    def on_bt_ta_seguent_clicked(self, widget, *args):
        print "on_bt_ta_seguent_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_ta_seguent_clicked }

    #-- Frmbrowse.on_bt_ta_darrer_clicked {
    def on_bt_ta_darrer_clicked(self, widget, *args):
        print "on_bt_ta_darrer_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_ta_darrer_clicked }

    #-- Frmbrowse.on_bt_sel_si_clicked {
    def on_bt_sel_si_clicked(self, widget, *args):
        print "on_bt_sel_si_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_sel_si_clicked }

    #-- Frmbrowse.on_bt_sel_cancel_clicked {
    def on_bt_sel_cancel_clicked(self, widget, *args):
        print "on_bt_sel_cancel_clicked called with self.%s" % widget.get_name()
    #-- Frmbrowse.on_bt_sel_cancel_clicked }


class DlgCercaAr(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="dlg_cerca_ar",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- DlgCercaAr.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- DlgCercaAr.new }

    #-- DlgCercaAr custom methods {
    #   Write your own methods here
    #-- DlgCercaAr custom methods }


class Frmcalendari(SimpleGladeApp):

    def __init__(self, path="gesjo5.glade",
                 root="calendari",
                 domain=app_name, **kwargs):
        path = os.path.join(glade_dir, path)
        SimpleGladeApp.__init__(self, path, root, domain, **kwargs)

    #-- Frmcalendari.new {
    def new(self):
        print "A new %s has been created" % self.__class__.__name__
    #-- Frmcalendari.new }

    #-- Frmcalendari custom methods {
 
    #-- Frmcalendari custom methods }

    #-- Frmcalendari.on_calendar_day_selected_double_click {
    def on_calendar_day_selected_double_click(self, widget, *args):
        print "on_calendar_day_selected_double_click called with self.%s" % widget.get_name()
    #-- Frmcalendari.on_calendar_day_selected_double_click }


#-- main {

def main():
    frmgesjo = Frmgesjo()
    frm_dl_esborra = FrmDlEsborra()
    dlg_cerca = DlgCerca()
    frmmarca = Frmmarca()
    frmtaller = Frmtaller()
    frmmecanic = Frmmecanic()
    frmbrowse = Frmbrowse()
    dlg_cerca_ar = DlgCercaAr()
    calendari = Calendari()

    frmgesjo.run()

if __name__ == "__main__":
    main()

#-- main }
